[workspace]
resolver = "2"
members = ["valide", "valide_derive"]

[workspace.package]
version = "0.0.1"
authors = ["Julian Ollivieira"]
repository = "https://github.com/snx-rs/valide"
license = "MIT"
